log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "loky13@daum.net"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web
tls:
  # https://docs.traefik.io/https/tls/#tls-options
  options:
    default:
      # see https://caniuse.com/tls1-2 for browsers that support TLS 1.2
      minVersion: VersionTLS12
      # see https://caniuse.com/sni for browsers that support SNI
      sniStrict: true
      # https://wiki.mozilla.org/Security/Server_Side_TLS
      cipherSuites: # use only elliptic curve (the strongest) ciphers
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

http:
  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

    security-headers:
      # https://docs.traefik.io/middlewares/headers/#general
      headers:
        # TODO increase stsSeconds to *at least* 31536000 (1 year) once HTTPS works
        stsSeconds: 60
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        customResponseHeaders:
          # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server
          server: jolzfjhabd # hide server version

    auth:
      basicAuth:
        users:
          - "nerdcollege:$apr1$mVQYRSjC$KzW7gqW39NsSnSSiV1r5o1"

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: nerd-college-network

# Docker 감시 옵션 추가
command:
  - "--providers.docker=true"
  - "--providers.docker.watch=true"